name: Main Workflow

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Install pnpm
      run: npm install -g pnpm

    - name: Use Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '14'

    - name: Install dependencies
      run: pnpm install

    - name: Run checkAndReportChatsUsage
      run: pnpm turbo run checkAndReportChatsUsage
      env:
        DATABASE_URL: ${{ secrets.DB_URL }}
