name: Main Workflow

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 14

      - name: Set DATABASE_URL
        run: echo "DATABASE_URL=postgresql://localhost:5432/mydb" >> $GITHUB_ENV

      - name: Install dependencies
        run: pnpm install

      - name: Run checkAndReportChatsUsage
        run: pnpm turbo run checkAndReportChatsUsage
