name: Main workflow

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup Node.js and environment
      uses: actions/setup-node@v2
      env:
        DATABASE_URL: ${{ secrets.DATABASE_URL }}

    - name: Install dependencies
      run: npm ci

    - name: Run checkAndReportChatsUsage task
      run: npm run checkAndReportChatsUsage
